---
title: ""
output:
   html_document:

       
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r setup, include=FALSE}
#### Set up workspace ####
library(dplyr)
library(highcharter)

knitr::opts_chunk$set(echo = FALSE)

# set global options to ensure that comma separator is a comma for highchart graphs
lang <- getOption("highcharter.lang")
lang$thousandsSep <- ","
options(highcharter.lang = lang)

```

```{r, include=FALSE}
#### Set themes and options ####
## COLORS ##
meteorite <- "#3A207D"
black <- "#000000"
alabaster<-"#FBFBFB"
gainsboro <- "#2B2B2B"

# define fonts in chart
main_font <- "Inter"
black_font_weight <- 900
regular_font_weight <- 400

# highchart theme 
# cc_theme <- hc_theme(colors = c(meteorite, "#991F7B", "#D8406A", "#FC7957"),
#                      chart = list(backgroundColor = alabaster,
#                                   style = list(fontFamily = main_font, # font_subtitle
#                                                fontWeight = black_font_weight,
#                                                color=alabaster)),
#                      title = list(style = list(color = black,
#                                                fontFamily = main_font, # font_title
#                                                fontWeight = black_font_weight,
#                                                textAlign="left",
#                                                fontSize='24px')),
#                      subtitle = list(style = list(color = black,
#                                                   fontFamily = main_font, # font_subtitle
#                                                   fontWeight = black_font_weight,
#                                                   textAlign="left",
#                                                   fontSize='14px')),
#                      caption = list(style = list(color = meteorite,
#                                                  fontFamily = main_font, #font_caption
#                                                  fontWeight = regular_font_weight,
#                                                  textAlign = "left",
#                                                  fontSize="8px"),
#                                     useHTML = TRUE),
#                      axis = list(style = list(color = gainsboro,
#                                               fontFamily =  main_font, # font_axis_label
#                                               fontWeight = regular_font_weight,
#                                               fontSize='12px')),
#                      xAxis=list(labels=
#                                   list(style=list(color=black,
#                                                   fontFamily = main_font, # font_x_label
#                                                   fontWeight = regular_font_weight,
#                                                   width=120,  #argument to modify the width of the labels,
#                                                   spacingLeft = "150px",
#                                                   fontSize="14px"))),
#                      yAxis=list(labels=
#                                   list(style=list(color=black,
#                                                   fontFamily= main_font, # font_axis_label
#                                                   fontWeight = regular_font_weight,
#                                                   fontSize="12px",
#                                                   margin = 50))),
#                      legend = list(itemStyle = 
#                                      list(fontFamily= main_font, # font_axis_label
#                                           fontWeight = regular_font_weight,
#                                           color = black),
#                                    itemHoverStyle = 
#                                      list(fontFamily= main_font, # font_table_text
#                                           fontWeight = regular_font_weight,
#                                           color = black),
#                                    plotLines=list(color=gainsboro)))
#(Theme colors Developed from online color generator based on meteorite https://mycolor.space/?hex=%233A207D&sub=1)
eoy_theme <- hc_theme(colors = c(meteorite, "#991F7B", "#D8406A", "#FC7957"),
                     chart = list(backgroundColor = alabaster,
                                  style = list(fontFamily = main_font, 
                                               fontWeight = black_font_weight,
                                               color=alabaster)),
              
                     title = list(align="center",
                                  style = list(color = black,
                                               fontFamily = main_font, 
                                               fontWeight = black_font_weight,
                                               fontSize='25px'),
                                  useHTML = TRUE),
                     subtitle = list(align="left",
                                     style = list(color = black,
                                                  fontFamily = main_font, 
                                                  fontWeight = black_font_weight,
                                                  fontSize='20px'),
                                     useHTML = TRUE),
                     caption = list(align="center",
                                    style = list(color = meteorite,
                                                 fontFamily = main_font, 
                                                 fontWeight = black_font_weight,
                                                 fontSize="22px"),
                                    useHTML = TRUE),
             
                     axis = list(style = list(color = gainsboro,
                                              fontFamily =  main_font,
                                              fontWeight = regular_font_weight,
                                              fontSize='14px')),
                     xAxis=list(labels=
                                  list(style=list(color=black,
                                                  fontFamily = main_font, 
                                                  fontWeight = regular_font_weight,
                                                  width=120,  #argument to modify the width of the labels,
                                                  fontSize="14px"))),
                     yAxis=list(visible = F, 
                                startOnTick = F, 
                                endOnTick = F, 
                                min = 0, 
                                max = 9200000,
                                labels=
                                  list(style=list(color=black,
                                                  fontFamily= main_font, # font_axis_label
                                                  fontWeight = regular_font_weight,
                                                  fontSize="12px",
                                                  margin = 50))))

```


```{r data-prep, include=FALSE}

# This Creates the data-frame for the Support & Revenue Barchart

support <- c("Contributions", "Contracts", "Grants", "Other Income")
revenue <- c(2359843, 1779856, 9018627, 66838)

df <- data.frame(support, revenue) %>% 
  mutate(percentage=paste0(round(revenue/sum(revenue)*100, 1), "%"),
         revenue_label = paste0("$", prettyNum(revenue, big.mark = ",", scientific = FALSE))) %>% 
  arrange(desc(revenue))

# order support based on highest to lowest revenue
support_order <- order(df$revenue, decreasing=TRUE)
df$support <- factor(df$support, levels = df$support[support_order])

# Total Support & Revenue: $13,225,164

```

```{r, echo=FALSE,out.width="100%", out.height="100%"}
# Bar Chart for Support and Revenue 
highchart() %>%
  hc_add_series(df,
       type = "bar",
       hcaes(x = support, y = revenue, group = support),
       dataLabels = list(enabled = TRUE,
                         format = '{point.revenue_label}')) %>%
  hc_tooltip(headerFormat= "",
             style = list(color = black, 
                          fontFamily = main_font, # font_subtitle
                          fontWeight = black_font_weight,
                          fontSize='16px'), # size of labels
             pointFormat = "{point.percentage:.1f}", 
             style = list(color = black, 
                          fontFamily = main_font, # font_subtitle
                          fontWeight = black_font_weight,
                          fontSize='14px')) %>%
  
  hc_yAxis(title = list(text = paste0(""))) %>%
  
  hc_xAxis(title = list(enabled = FALSE, 
                        text = paste0("")),
           crosshair=TRUE) %>%
  
  hc_title(text = "Statement of Activities") %>% 
  
  hc_subtitle(text = "Support and Revenue") %>%
  
  hc_caption(text = "Total Support & Revenue: $13,225,164") %>%
  
  hc_add_theme(eoy_theme)  %>% 
  
  hc_size(700, 480)

```
<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>
